apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: "sameermaner"
  password: "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"
