apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  steps:
    - name: git-clone
      image: alpine/git:2.40.1
      script: |
        #!/bin/sh
        git clone https://github.com/sameermaner/tekton-test-repo .
