apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-pipeline-run-workspace-demo
spec:
  pipelineRef:
    name: example-pipeline-workspace-demo
  workspaces:
    - name: messages # this workspace name must be declared in the Task
      persistentVolumeClaim:
        claimName: tekton-test-claim
