apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-uppercase-pipeline
spec:
  tasks:
    - name: task-process-input
      taskRef:
        name: uppercase-task-with-input-and-result
      params:
        - name: input-message
          value: "Hello fellow people!"
    - name: print-message
      taskRef:
        name: echo-task-with-input
      params:
        - name: input-message
          value: "$(tasks.task-process-input.results.output-message)"
